tap 'homebrew/bundle'
tap 'homebrew/x11'
tap 'neovim/neovim'
tap 'rogual/neovim-dot-app'

brew 'boot-clj'
brew 'bro'
brew 'ctags'
brew 'elixir'
brew 'git', args: ['without-completions']
brew 'git-flow-avh'
brew 'haskell-stack'
brew 'leiningen'
brew 'macvim'
brew 'markdown'
brew 'nginx'
brew 'node'
brew 'planck'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'rename'
brew 'rlwrap'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'homebrew/x11/swi-prolog'
brew 'neovim/neovim/neovim'
brew 'rogual/neovim-dot-app/neovim-dot-app', args: ['HEAD']

tap 'caskroom/cask'
brew 'brew-cask'
cask 'karabiner'
