tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'neovim/neovim'

brew 'boot-clj'
brew 'cmus'
brew 'fasd'
brew 'git', args: ['without-completions']
brew 'git-flow-avh'
brew 'leiningen'
brew 'lua'
brew 'markdown'
brew 'nginx'
brew 'node'
brew 'peco'
brew 'planck'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'rename'
brew 'rlwrap'
brew 'ruby'
brew 'rust'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'neovim'

cask 'gimp'
cask 'hammerspoon'
cask 'karabiner'
cask 'karabiner-elements'
cask 'keepassxc'
cask 'smcfancontrol'
cask 'xquartz'
