#!/usr/bin/env bash
set -o errexit
([[ -n "$DEBUG" ]] || [[ -n "$TRACE" ]]) && set -o xtrace

task_init_dotfiles () {
    git pull && git submodule init &&
        git pull --recurse-submodules &&
        git submodule update --recursive
}

task_brew () {
    hash brew || (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)")
    brew update
    brew bundle -v
}

task_fonts () {
    (cd fonts; ./install.sh)
}

task_gitconfig () {
    read -p 'git config user.email please: ' git_config_user_email
    git config --global user.email "$git_config_user_email"
    for i in $(ls ./git/hooks/*.tmpl); do
        ln -f "$i" "/usr/local/share/git-core/templates/hooks/$(basename $i .tmpl)"
    done
}

task_neovim () {
    pip3 install neovim-remote
    pip install --upgrade neovim
    mkdir -p ~/.config/nvim/ftplugin
    mkdir -p ~/.config/nvim/undo
}

task_opt () {
    sudo mkdir -p /opt/dotfiles
    sudo chown $USER /opt/dotfiles
    ln -Ffs opt /opt/dotfiles
    for i in $(ls opt); do
        echo "installing opt: ${i}"
        zsh -c "cd opt/${i}; ./${i}.install"
    done
}

task_ruby () {
    bundle install
}

task_lua() {
    luarocks install fennel
}

task_all () {
    task_init_dotfiles
    task_brew
    task_ruby
    task_luarocks
    task_fonts
    task_gitconfig
    task_neovim
    task_opt
}

main() {
    [[ ! "$(pwd)" == "$HOME/dotfiles" ]] && (echo 'CANNOT EXECUTE outside of dotfiles root'; exit 2)
    case "$1" in
        '') task_all && exec zsh zsh/zshrc ;;
        brew) task_brew ;;
        gitconfig|git) task_gitconfig ;;
        help) echo "init brew gitconfig neovim opt" ;;
        init) task_init_dotfiles ;;
        neovim|nvim|vim) task_neovim ;;
        opt) task_opt ;;
        ruby) task_ruby ;;
        lua) task_lua ;;
        *) echo "Failed to recognize: '$@'" && exit 1 ;;
    esac
}
main "$@"
