alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gsw='git checkout'
alias gd='git diff --color-words'
alias gds='gd --staged'
alias gs='git status'
alias gc='git commit --verbose'
alias gca='git commit --verbose --all'
alias gr='git reset'
alias gmb='git merge-base HEAD'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gpush='git push && git push --tags'
alias gp='git push'
alias gpf='git push --force-with-lease --force-if-includes'
alias gpb='git push -u origin HEAD'
alias gshow='git show --color-words'
alias gstash='git stash'
alias gsave='git stash save'
alias gl='GIT_PAGER="less -p \"\(HEAD\"" git log --graph --all --decorate --abbrev-commit'

alias gundo='git reset --soft HEAD~'
alias gredo='git commit --verbose -c ORIG_HEAD'

alias gf='git flow'
alias gff='git flow feature'
alias gffs='gff start'
alias gfff='gff finish'
alias gffp='gff publish'
alias gfr='git flow release'
alias gfrs='gfr start'
alias gfrf='git flow release finish'
