alias ga='git add'
alias gaa='git add --all'
alias gc='git commit --verbose'
alias gca='git commit --verbose --all'
# ./ai.zsh defines gcai -> edit git commit message initialized by ai
alias gd='git diff --color-words'
alias gds='gd --staged'
alias gl='git log --graph --all --decorate --abbrev-commit'
alias gs='git status'
alias gsave='git stash save'
alias gshow='git show --color-words'
alias gstash='git stash'
alias gsw='git checkout'

alias gp='echo "ERROR: USE: vim git fuGITive (whichkey plugin)"; return 1'
alias gpf='echo "ERROR: USE: vim git fuGITive (whichkey plugin)"; return 1'
alias gpl='echo "ERROR: USE: vim git fuGITive (whichkey plugin)"; return 1'
