alias ga='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git add'
alias gaa='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git add --all'
alias gsw='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git checkout'
alias gd='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git diff --color-words'
alias gds='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && gd --staged'
alias gs='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git status'
alias gc='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git commit --verbose'
alias gca='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git commit --verbose --all'
alias gpl='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git pull'
alias gplr='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git pull --rebase'
alias gp='echo "ERROR: USE: vim git ;gppp (whichkey plugin)"'
alias gpf='echo "ERROR: USE: vim git ;gppf (whichkey plugin)"'
alias gpb='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git push -u origin HEAD'
alias gshow='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git show --color-words'
alias gstash='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git stash'
alias gsave='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git stash save'
alias gl='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && GIT_PAGER="less -p \"\(HEAD\"" git log --graph --all --decorate --abbrev-commit'

alias gundo='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git reset --soft HEAD~'
alias gredo='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git commit --verbose -c ORIG_HEAD'

alias gf='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git flow'
alias gff='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git flow feature'
alias gffs='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && gff start'
alias gfff='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && gff finish'
alias gffp='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && gff publish'
alias gfr='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git flow release'
alias gfrs='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && gfr start'
alias gfrf='echo "WARNING: PREFER VIM WHICH KEY" && echo "ack?" && read && git flow release finish'
