#!/usr/bin/env zsh

for f in `git diff --name-only --staged`; do
    echo $f
    ag 'test/focused' $f \
        && echo "[pre-commit/error]: Found focused tests!" >&2 \
        && exit 1
done

exit 0
