#!/usr/bin/env fish

set -l staged_changes (git diff --staged --unified=0)

echo $staged_changes | ag '^\+' | ag 'test/focused'
and echo "[pre-commit/ERROR]: Found focused tests!" >&2
and exit 11

echo $staged_changes | ag '^\+' | ag 'test/ignored'
and echo "[pre-commit/ERROR]: Found ignored tests!" >&2
and exit 12

echo $staged_changes | ag '^\+' | ag 'tap>'
and echo "[pre-commit/ERROR]: Found calls to tap>!" >&2
and exit 13

echo $staged_changes | ag '^\+' | ag 'RESUMEHERE'
and echo "[pre-commit/ERROR]: Found RESUMEHERE markers!" >&2
and exit 14

set -l markers (echo $staged_changes | ag '^\+' | ag 'TASK')
if test -n "$markers"
    echo "[pre-commit/ERROR]: Found staged TASK markers:"
    echo $markers
    exit 15
end

#git flow config &> /dev/null \
#  || echo "[pre-commit/WARNING]: Not a gitflow-enabled repo yet. Please run 'git flow init' first."

#set -l dev_branch (git flow config 2>/dev/null | ag -o 'development: (\w+)' | ag -o '\w+$'; or echo 'master')
#
#set -l markers (git diff $dev_branch...HEAD | ag '^\+' | ag 'TASK')
#if test -n "$markers"
#    echo "[pre-commit/ERROR]: Found TASK markers in branch:"
#    echo $markers
#    exit 16
#end

if string match -q '*pre_commit*' (cmds list)
    cmds pre_commit
    exit $status
end

exit 0
