#!/usr/bin/env bash
([[ "$DEBUG" ]] || [[ "$TRACE" ]]) && set -o xtrace
#Put the branch/name into the template.
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
#Check is not amend & we have a branch with a slash (eg: feature/foo)
if [ -z "$(head -n1 $1)" ] && [ "$(dirname $branch)" != "." ] && [ ! -z "$(basename $branch)" ]; then
    sed -i '' "1s/^/$(basename $branch) -> /" $1
fi
