#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Anthony D'Ambrosio"
email = "anthony.dayzerostudio@gmail.com"

[revsets]
log = "all() ~ (description(exact:\"\") ~ @)"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: Lines starting with \"JJ: \" (like this one) will be removed.\n",
  "JJ:\n",
  "JJ: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n",
  "JJ: 🛑  To ABORT:  exit with nonzero status  →  :cq  (or XX, my nvim only)\n",
  "JJ: ⚠️   Empty description is VALID in jj — it will NOT abort!\n",
  "JJ: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n",
)
'''

log = '''
concat(
  "commit " ++ commit_id.short() ++ " " ++ bookmarks ++ " " ++ remote_bookmarks ++ tags ++ if(self.contained_in("first_parent(@)"), " HEAD") ++ "\n",
  "Author: " ++ author.name() ++ " <" ++ author.email() ++ ">\n",
  "Date:   " ++ author.timestamp().local().format("%a %b %d %H:%M:%S %Y %z") ++ "\n",
  "\n",
  indent("    ", if(description, description, "(no description set)\n")),
  "\n",
)
'''
