alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gsw='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gs='git status'
alias gc='git commit'
alias gca='git commit --all'
alias gr='git reset'
alias pull='git pull'
alias push='git push && git push --tags'
alias show='git show'
alias stash='git stash'
alias save='git stash save'
alias gl='GIT_PAGER="less -p \"\(HEAD\"" git log --graph --all --decorate --abbrev-commit'

alias gundo='git reset --soft HEAD~'
alias gredo='git commit -c ORIG_HEAD'

alias gf='git flow'
alias gff='git flow feature'
alias gffs='git flow feature start'
alias gfff='git flow feature finish'
alias gfr='git flow release'
alias gfrs='git flow release start'
alias gfrf='git flow release finish'
