export SHELL=/bin/zsh
#git (& ∴ less) doesn't show UTF-8 file properly
export LESSCHARSET=UTF-8

for env in $(ls `dirname $0`/env); do
    source ~/dotfiles/zsh/env/"${env}"
done

[ -e ~/dotfiles/extra.env.zsh ] && source ~/dotfiles/extra.env.zsh
